//
//  StudentInformation.swift
//  OnTheMap2
//
//  Created by Fabio Tiberio on 19/04/21.
//

import Foundation

struct StudentInformation: Codable {
    // an auto-generated id/key generated by Parse which uniquely identifies a StudentInformation
    var objectId: String?
    // the Udacity account id
    var uniqueKey: String?
    var firstName: String?
    var lastName: String?
    var mapString: String?
    var mediaURL: String?
    var latitude: Double?
    var longitude: Double?
    var createdAt: String?
    var updatedAt: String?
}
